export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/local/sbin/"
export PATH="$PATH:/usr/local/smlnj/bin"
export PATH="$PATH:/usr/local/opt/llvm/bin"
export PATH="$PATH:/usr/local/opt/openjdk/bin"
export PATH="$PATH:$HOME/Downloads"
export PATH="$PATH:$HOME/.emacs.d/bin"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/tmp/cc0/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:$HOME/code/tcmd"
export PATH="$PATH:$HOME/.npm-global-pkgs/bin"
export PATH="$PATH:$HOME/code/brutus"
export PATH="$PATH:/Users/michaellan/scripts"
export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"

export EDITOR="nvim"
export PAGER="less"

export JAVA_HOME="/usr/local/opt/openjdk"
export FWMM_DIR="$HOME/.local/share/fwmm"
export NVM_DIR="$HOME/.nvm"
