[user]
name = "Michael Lan"
email = "..."

[ui]
default-command = ["log", "--no-pager"]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
'format_short_signature(signature)' = 'signature.email().local()'
'format_short_id(id)' = 'id.shortest()'
