#!/bin/sh

requires() {
  for cmd in "$@"; do
    if ! command -v "$cmd"; then
     echo "<$cmd> cmd not found"
     exit 1
    fi
  done
}

add_still_image_to_audio() {
  requires ffmpeg
  image=$1
  audio=$2
  outfile=$3
  ffmpeg -loop 1 -i "$image" -i "$audio" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p -shortest "$outfile"
}

flac_to_m4a() {
  requires ffmpeg
  input=$1
  outfile=$2
  ffmpeg -i "$input" -c:a alac -c:v copy "$outfile"
}

create_gif_from_portion_of_video() {
  requires ffmpeg convert
  video=$1
  outfile=$2
  skipstart=$3
  duration=$4
  ffmpeg -ss "$skipstart" -t "$duration" -i "$video" -vf "fps=10,scale=1000:-1:flags=lanczos" -c:v pam -f image2pipe - | convert -delay 10 - -loop 0 -layers optimize "$outfile"
}
