#!/usr/bin/env bash

# stdin
TTS="say"

if [[ "$OSTYPE" == "darwin"* ]]; then
  PASTE_CMD=gpaste
else
  PASTE_CMD=paste
fi

str=$(cat /dev/stdin | sed 's/[^A-Za-z]//g' | $PASTE_CMD -sd '')
echo $str
echo "length ${#str}"
idx=0
while (( idx < ${#str} ))
do
   char=${str:$idx:1}
   no=$(( idx + 1 ))
   echo "$no,$char" | $TTS
   (( idx += 1 ))
done
