#!/usr/bin/osascript

# Open a PDF to a given page number using Skim (macOS)
# $1 is path to PDF
# $2 is page number

on run argv
    set fileName to (item 1 of argv)
    set pageNum to (item 2 of argv) as integer

    tell application "Skim"
        open fileName
        tell document 1 to go to page pageNum
        activate
    end tell
end run
